# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dut_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64ut_service.proto\x12\x03\x64ut\"\x10\n\x0e\x43onnectRequest\"3\n\x0f\x43onnectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\" \n\x0bReadRequest\x12\x11\n\tparameter\x18\x01 \x01(\t\"0\n\x0cReadResponse\x12\x11\n\tparameter\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\";\n\x0f\x46irmwareRequest\x12\x15\n\rfunction_name\x18\x01 \x01(\t\x12\x11\n\targuemtns\x18\x02 \x01(\t\"4\n\x10\x46irmwareResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xc0\x01\n\nDUTService\x12\x39\n\x0c\x43onnectToDUT\x12\x13.dut.ConnectRequest\x1a\x14.dut.ConnectResponse\x12\x32\n\x0bReadDUTInfo\x12\x10.dut.ReadRequest\x1a\x11.dut.ReadResponse\x12\x43\n\x14\x43\x61llFirmwareFunction\x12\x14.dut.FirmwareRequest\x1a\x15.dut.FirmwareResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dut_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONNECTREQUEST']._serialized_start=26
  _globals['_CONNECTREQUEST']._serialized_end=42
  _globals['_CONNECTRESPONSE']._serialized_start=44
  _globals['_CONNECTRESPONSE']._serialized_end=95
  _globals['_READREQUEST']._serialized_start=97
  _globals['_READREQUEST']._serialized_end=129
  _globals['_READRESPONSE']._serialized_start=131
  _globals['_READRESPONSE']._serialized_end=179
  _globals['_FIRMWAREREQUEST']._serialized_start=181
  _globals['_FIRMWAREREQUEST']._serialized_end=240
  _globals['_FIRMWARERESPONSE']._serialized_start=242
  _globals['_FIRMWARERESPONSE']._serialized_end=294
  _globals['_DUTSERVICE']._serialized_start=297
  _globals['_DUTSERVICE']._serialized_end=489
# @@protoc_insertion_point(module_scope)
