# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dut_service_pb2 as dut__service__pb2


class DUTServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConnectToDUT = channel.unary_unary(
                '/dut.DUTService/ConnectToDUT',
                request_serializer=dut__service__pb2.ConnectRequest.SerializeToString,
                response_deserializer=dut__service__pb2.ConnectResponse.FromString,
                )
        self.ReadDUTInfo = channel.unary_unary(
                '/dut.DUTService/ReadDUTInfo',
                request_serializer=dut__service__pb2.ReadRequest.SerializeToString,
                response_deserializer=dut__service__pb2.ReadResponse.FromString,
                )
        self.CallFirmwareFunction = channel.unary_unary(
                '/dut.DUTService/CallFirmwareFunction',
                request_serializer=dut__service__pb2.FirmwareRequest.SerializeToString,
                response_deserializer=dut__service__pb2.FirmwareResponse.FromString,
                )


class DUTServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConnectToDUT(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDUTInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallFirmwareFunction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DUTServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConnectToDUT': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectToDUT,
                    request_deserializer=dut__service__pb2.ConnectRequest.FromString,
                    response_serializer=dut__service__pb2.ConnectResponse.SerializeToString,
            ),
            'ReadDUTInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDUTInfo,
                    request_deserializer=dut__service__pb2.ReadRequest.FromString,
                    response_serializer=dut__service__pb2.ReadResponse.SerializeToString,
            ),
            'CallFirmwareFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.CallFirmwareFunction,
                    request_deserializer=dut__service__pb2.FirmwareRequest.FromString,
                    response_serializer=dut__service__pb2.FirmwareResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dut.DUTService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DUTService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConnectToDUT(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dut.DUTService/ConnectToDUT',
            dut__service__pb2.ConnectRequest.SerializeToString,
            dut__service__pb2.ConnectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadDUTInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dut.DUTService/ReadDUTInfo',
            dut__service__pb2.ReadRequest.SerializeToString,
            dut__service__pb2.ReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CallFirmwareFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dut.DUTService/CallFirmwareFunction',
            dut__service__pb2.FirmwareRequest.SerializeToString,
            dut__service__pb2.FirmwareResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
