# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: harness_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15harness_service.proto\x12\x07harness\" \n\x0bTestRequest\x12\x11\n\ttest_name\x18\x01 \x01(\t\"I\n\x0cTestResponse\x12\x11\n\ttest_name\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x16\n\x0e\x65xecution_time\x18\x03 \x01(\x02\"\x10\n\x0e\x43onnectRequest\"3\n\x0f\x43onnectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x8b\x01\n\x0eHarnessService\x12\x36\n\x07RunTest\x12\x14.harness.TestRequest\x1a\x15.harness.TestResponse\x12\x41\n\x0c\x43onnectToDUT\x12\x17.harness.ConnectRequest\x1a\x18.harness.ConnectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'harness_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TESTREQUEST']._serialized_start=34
  _globals['_TESTREQUEST']._serialized_end=66
  _globals['_TESTRESPONSE']._serialized_start=68
  _globals['_TESTRESPONSE']._serialized_end=141
  _globals['_CONNECTREQUEST']._serialized_start=143
  _globals['_CONNECTREQUEST']._serialized_end=159
  _globals['_CONNECTRESPONSE']._serialized_start=161
  _globals['_CONNECTRESPONSE']._serialized_end=212
  _globals['_HARNESSSERVICE']._serialized_start=215
  _globals['_HARNESSSERVICE']._serialized_end=354
# @@protoc_insertion_point(module_scope)
