# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import harness_service_pb2 as harness__service__pb2


class HarnessServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunTest = channel.unary_unary(
                '/harness.HarnessService/RunTest',
                request_serializer=harness__service__pb2.TestRequest.SerializeToString,
                response_deserializer=harness__service__pb2.TestResponse.FromString,
                )
        self.ConnectToDUT = channel.unary_unary(
                '/harness.HarnessService/ConnectToDUT',
                request_serializer=harness__service__pb2.ConnectRequest.SerializeToString,
                response_deserializer=harness__service__pb2.ConnectResponse.FromString,
                )


class HarnessServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectToDUT(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HarnessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunTest': grpc.unary_unary_rpc_method_handler(
                    servicer.RunTest,
                    request_deserializer=harness__service__pb2.TestRequest.FromString,
                    response_serializer=harness__service__pb2.TestResponse.SerializeToString,
            ),
            'ConnectToDUT': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectToDUT,
                    request_deserializer=harness__service__pb2.ConnectRequest.FromString,
                    response_serializer=harness__service__pb2.ConnectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'harness.HarnessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HarnessService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/harness.HarnessService/RunTest',
            harness__service__pb2.TestRequest.SerializeToString,
            harness__service__pb2.TestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConnectToDUT(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/harness.HarnessService/ConnectToDUT',
            harness__service__pb2.ConnectRequest.SerializeToString,
            harness__service__pb2.ConnectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
