# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instrument_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18instrument_service.proto\x12\ninstrument\"\r\n\x0bInitRequest\"0\n\x0cInitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2_\n\x11InstrumentService\x12J\n\x15InitializeInstruments\x12\x17.instrument.InitRequest\x1a\x18.instrument.InitResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'instrument_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INITREQUEST']._serialized_start=40
  _globals['_INITREQUEST']._serialized_end=53
  _globals['_INITRESPONSE']._serialized_start=55
  _globals['_INITRESPONSE']._serialized_end=103
  _globals['_INSTRUMENTSERVICE']._serialized_start=105
  _globals['_INSTRUMENTSERVICE']._serialized_end=200
# @@protoc_insertion_point(module_scope)
